admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8001
  tls:
    enabled: false
    parameters: []
  ingress:
    hostname: admin-kong.icurity.cloud
    enabled: true
    ingressClassName: nginx
proxy:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: admin-kong.icurity.cloud
    path: /proxy
    ingressClassName: nginx
ingressController:
  enabled: false
manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8002
  tls:
    enabled: false
    servicePort: 443
    containerPort: 8445
    parameters:
    - http2
  ingress:
    hostname: manager-kong.icurity.cloud
    enabled: true
    ingressClassName: nginx
portal:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8003
  tls:
    enabled: false
  ingress:
    enabled: true
    hostname: admin-kong.icurity.cloud
    path: /dev-portal
    ingressClassName: nginx
portalapi:
  enabled: false
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
